language: python
sudo: true
dist: trusty

python:
  - 3.5
branches:
  only:
    - master
    - develop
notifications:
  email: false

addons:
  apt:
    packages:
      - libgl1-mesa-dri
      - libegl1-mesa
      - cmake
      - xorg-dev
      - libglu1-mesa-dev
      - mercurial
      - libdbus-1-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpulse-dev
      - libx11-dev
      - libxcursor-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev
      - libxt-dev
      - libxv-dev
      - libxxf86vm-dev
      - libasound2-dev
      - libts-dev
      - libudev-dev

env:
  - PYTEST_QT_API=pyqt5

jdk:
  - oraclejdk7

before_install:
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - sudo apt-get update
  - sudo apt-get install -y xvfb
  # install Neo4j locally:
  - bash continuous-integration/travis/install.sh
  - ls $HOME/neo4j/neo4j

# Install packages
install:
  - export PATH="$HOME/miniconda/miniconda/bin:$PATH"
  - source activate test-environment
  - which python
  - conda list

before_script:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render


# Run test
script:
  - $HOME/neo4j/neo4j/bin/neo4j start
  - coverage run --source=speechtools setup.py test

# Calculate coverage
after_success:
  - coveralls

cache:
  apt: true
  pip: true
  directories:
    - $HOME/miniconda
    - $HOME/neo4j
